### ISSUE TITLE
Incomplete comparison of test results with reference data

### ISSUE THREAD

**Issue by i-and** [eProsima/Micro-CDR#50]
1. It looks like in the files ArrayEndianness.cpp, SequenceEndianness.cpp, ArraySerialization.hpp and SequenceSerialization.hpp incorrect use of the std::mecmp() function: the third argument is the number of elements in the array, not the size in bytes (as it should be):
~~~
EXPECT_TRUE(0 == std::memcmp(input, output, ARRAY_SIZE)); 
EXPECT_TRUE(0 == std::memcmp(input, output, SEQUENCE_SIZE));
EXPECT_TRUE(0 == std::memcmp(input, output, sequence_size)); 
~~~
This incomplete comparison of the actual and reference array may result in missing testing errors.

I propose to change it as follows:
~~~
EXPECT_TRUE(0 == std::memcmp(input, output, ARRAY_SIZE * sizeof(input[0]))); 
EXPECT_TRUE(0 == std::memcmp(input, output, SEQUENCE_SIZE * sizeof(input[0])));
EXPECT_TRUE(0 == std::memcmp(input, output, sequence_size * sizeof(input[0]))); 
~~~

2. In test functions, I suggest initializing the elements of the output[] array with the value '0'. This will give determinism to the process of comparing the input[] and output[] arrays.

**Comment by julibert** [comment]
Hi @i-and,
Thank you for helping us to improve our tests. We will fix it as soon as possible.

**Comment by pablogs9** [comment]
Closing: https://github.com/eProsima/Micro-CDR/pull/66
