### ISSUE TITLE
set_common_compile_options(..) 'forces' C++ language on

### ISSUE THREAD

**Issue by gavanderhoorn** [eProsima/Micro-CDR#57]
Trying to build Micro-CDR on a platform without (proper) C++ support, I noticed that even though the top-level `CMakeLists.txt` only enabled C:

https://github.com/eProsima/Micro-CDR/blob/6c9a88f122565d4c6e768ceae802c32e4a2ee836/CMakeLists.txt#L51

it then continues and includes `cmake/common/check_configuration.cmake`, which does:

https://github.com/eProsima/Micro-CDR/blob/6c9a88f122565d4c6e768ceae802c32e4a2ee836/cmake/common/check_configuration.cmake#L115-L117

which ends up testing my platform's C++ compiler and fails.

Commenting the `enable_language(CXX)` makes everything work (the C-side is fine).

**Comment by gavanderhoorn** [comment]
Perhaps something like:

```cmake
if("CXX" IN_LIST languages)
  ...
endif()
```

could be used?

Not sure how to merge that with the rest of the function though. It already seems to check whether `CXX` is enabled / used for the `target` arg.

Should those `enable_language(..)` calls be there?

**Comment by gavanderhoorn** [comment]
So far I've been using a fork, but it would be great if this could be resolved here.

Any ideas?

**Comment by gavanderhoorn** [comment]
Ping @pablogs9?

**Comment by pablogs9** [comment]
I think it is safe to remove `enable_language(CXX)`, can you open a PR?

**Comment by gavanderhoorn** [comment]
The same thing happens in `eProsima/Micro-XRCE-DDS-Client` btw: [here](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/69134a9ba97f98f3cfad1588af816a6a22133116/cmake/common/check_configuration.cmake#L117).

That also seems to be a C-only project.

Would you accept a PR there as well?

**Comment by pablogs9** [comment]
Yes, we have to check if there is some problem with tests... Please open and let see whats happens with the CI.

**Comment by pablogs9** [comment]
Both merged

**Comment by pablogs9** [comment]
Thanks

**Comment by gavanderhoorn** [comment]
Thanks again.
