### ISSUE TITLE
[feature request] Add 'length' field to MicroBuffer

### ISSUE THREAD

**Issue by TSC21** [eProsima/micro-CDR#6]
`MicroBuffer` [constructor/struct](https://github.com/eProsima/micro-CDR/blob/master/include/microcdr/microcdr.h#L49-L60) doesn't currently have a length field. To copy the buffer content into an interface or streaming protocol, we require the length to be available, in order to fill the payload according to the size. Though the length could be computed using `final - init`, I consider to be more beneficial to have that available out-of-the-box on the constructor.

**Comment by TSC21** [comment]
@BorjaOuterelo is that something you will consider to get in?

**Comment by BorjaOuterelo** [comment]
Hi @TSC21, we have an ongoing new revision of MicroBuffer.
In this new release we have added:
`uint32_t micro_buffer_length(MicroBuffer* buffer); `
and
`uint32_t micro_buffer_remaining(MicroBuffer* buffer);`

These functions will calculate `final - init` and `final - iterator` respectively.

Hopefully, this suits your needs.

**Comment by TSC21** [comment]
Yes those seem important. When is the new iteration going to be released?

**Comment by TSC21** [comment]
@BorjaOuterelo thank you! Do you recommend pushing https://github.com/PX4/Firmware/pull/9651 to latest master or wait for your tag? When is it planned?

**Comment by BorjaOuterelo** [comment]
@TSC21 The tag needs at least two weeks to be ready but I can not assure you any date yet.
I think you can upgrade to the latest master commit and wait there for the tag; probably this will be the point of the tag.

**Comment by TSC21** [comment]
This can be closed now. Thanks for the feature!
